# Generated by Django 5.2.8 on 2025-11-25 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("resumen", models.TextField()),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="articulo_por_defecto.png",
                        null=True,
                        upload_to="media",
                    ),
                ),
                ("publicado", models.DateField(default=django.utils.timezone.now)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articulo.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="articulo/articulo_por_defecto.png",
                        null=True,
                        upload_to="articulo",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="articulo.articulo",
                    ),
                ),
            ],
        ),
    ]
